### ISSUE TITLE
Multiline mode

### ISSUE THREAD

**Issue by sobolevn** [google/semantic-release-replace-plugin#139]
Right now it is impossible to write your `from` regex as `^version = ...` because regex is not in multiline mode.
Source: https://github.com/google/semantic-release-replace-plugin/blob/master/src/index.ts#L108

Right now both these lines match `"from": "version = \".*\"",` regex:

```ini
[tool.poetry]
version = "1.4.0"
```

and 

```ini
[tool.poetry.dependencies]
django-reversion = "^3.0"
```

I know that I can rewrite my `from` regex to be stricter on version value, but the easiest way is `^version = \".*\"`, which is impossible right now.
I also don't want to write something like `version = \"\d+\.\d+\.\d+\"` because:
1. It still can match `django-reversion = "3.0.1"` if I ever want to pin it
2. It won't match `-pre` and `-beta` suffixes and I don't want to make this regex overly complex or sensetive

**Comment by sobolevn** [comment]
Awesome! Would you be so kind to release a new version?

**Comment by jpoehnelt** [comment]
Yeah, currently the release is failing and I haven't had time to debug. I use the same pattern for numerous other packages. I will investigate further Monday.
