### ISSUE TITLE
Increment value

### ISSUE THREAD

**Issue by prisonerjohn** [google/semantic-release-replace-plugin#45]
Not an issue but more of a question:
Could this be used to increment a value, for example a build number?
Something like
```
  "from": "__BUILD__ = \"(\d+)\"",
  "to": "__BUILD__ = \"{$1+1}\"",
```
I'm not sure what the syntax would be...
Thanks!

**Comment by jpoehnelt** [comment]
I believe that should be supported along with many different options available in lodash [template](https://lodash.com/docs/4.17.15#template). Please report back if you get something like that working!

**Comment by jpoehnelt** [comment]
@prisonerjohn Where you able to achieve what you want here?

**Comment by prisonerjohn** [comment]
Hey, I'm a bit of a newbie with all this and did not really understand what you meant :) 

I followed the link to see what lodash is, but I'm not clear on how it fits into this plugin or semantic-release. I wanted to do a bit of research before writing back but didn't get around to it yet.

If you're cleaning up issues, you can close this and I can reopen when I get around to it.
